/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.vistas.gestion;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityGraph;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.FlushModeType;
import javax.persistence.LockModeType;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.StoredProcedureQuery;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.CriteriaUpdate;
import javax.persistence.metamodel.Metamodel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.control.AeropuertoJpaController;
import proyecto.control.AvionJpaController;
import proyecto.control.RefAeropuertJpaController;
import proyecto.control.VistaAvionesJpaController;
import proyecto.control.VistaVuelosJpaController;
import proyecto.control.VueloJpaController;
import proyecto.control.exceptions.NonexistentEntityException;
import proyecto.entidades.Aeropuerto;
import proyecto.entidades.RefAeropuert;
import proyecto.entidades.Vuelo;
import proyecto.entidades.Avion;
import proyecto.entidades.VistaVuelos;
import proyecto.entidades.VistaAviones;

/**
 *
 * @author David
 */
public class GestionVuelo extends javax.swing.JFrame {
    private static DefaultTableModel vuelosModel;
    private static DefaultTableModel ModelTableAeropuertos;
    private static DefaultTableModel ModelTableAviones;
    private static AvionJpaController avionesController = new AvionJpaController();
    private static VueloJpaController vuelosController = new VueloJpaController();
    private static AeropuertoJpaController aeropuertoController = new AeropuertoJpaController();
    private static RefAeropuertJpaController refController = new RefAeropuertJpaController();
    private static VistaVuelosJpaController vistaVuelosController = new VistaVuelosJpaController();
    private static VistaAvionesJpaController vistaAvionesController = new VistaAvionesJpaController();
    private static int idVueloMain;
    private static EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proyecto_DespegarPU");;
    private static EntityManager em = emf.createEntityManager();
    
    
    /**
     * Creates new form GestionVuelo
     */
    public GestionVuelo() {
        initComponents();
        listarAeropuertos();
        listarVuelos();

        listarAviones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        origenVuelo = new javax.swing.JLabel();
        destinoVuelo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vacantesVuelo = new javax.swing.JLabel();
        guardaVuelo = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        eliminarVuelo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        origenReferencia = new javax.swing.JLabel();
        destinoReferencia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVuelos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        registrarAeropuerto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelarRegAeropuertos = new javax.swing.JButton();
        idOrigen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idDestino = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listaAviones = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tiempoEstimadoVuelo = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        listaAeropuertos = new javax.swing.JTable();
        fechaVuelo = new com.toedter.calendar.JDateChooser();
        idAvion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        origenVuelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        destinoVuelo.setBackground(new java.awt.Color(255, 255, 255));
        destinoVuelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Formulario de Vuelo");

        guardaVuelo.setText("Guardar");
        guardaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaVueloActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        eliminarVuelo.setText("Eliminar");
        eliminarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVueloActionPerformed(evt);
            }
        });

        jLabel10.setText("Origen:");

        jLabel11.setText("Destino:");

        origenReferencia.setText("Ubicacion");

        destinoReferencia.setText("Ubicacion");

        listaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listaVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaVuelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaVuelos);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Seleccione los aeropuertos de origen y destino");

        registrarAeropuerto.setText("Agregar");
        registrarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarAeropuertoActionPerformed(evt);
            }
        });

        jLabel1.setText("Id avion:");

        jLabel2.setText("Origen:");

        cancelarRegAeropuertos.setText("Cancelar");
        cancelarRegAeropuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRegAeropuertosActionPerformed(evt);
            }
        });

        jLabel3.setText("Destino:");

        jLabel4.setText("Fecha:");

        jLabel13.setText("IdAvion");

        jLabel5.setText("Vacantes:");

        jLabel14.setText("IdAvion");

        jLabel6.setText("Precio estimado");

        listaAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listaAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAvionesMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(listaAviones);

        tiempoEstimadoVuelo.setText("0.0");
        jScrollPane5.setViewportView(tiempoEstimadoVuelo);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Seleccione un avión");

        listaAeropuertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        listaAeropuertos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAeropuertosMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(listaAeropuertos);

        idAvion.setBackground(new java.awt.Color(255, 255, 255));
        idAvion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Gestion de vuelos");

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(585, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(497, 497, 497))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(regresar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(guardaVuelo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Cancelar)
                                            .addGap(18, 18, 18)
                                            .addComponent(eliminarVuelo))
                                        .addComponent(fechaVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(idAvion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(origenVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(destinoVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vacantesVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(279, 279, 279)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel11)))
                                        .addComponent(registrarAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(origenReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(destinoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel13))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(idDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(idOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(cancelarRegAeropuertos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel7)
                .addGap(271, 271, 271)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(regresar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(idAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(origenVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(destinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(fechaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(20, 20, 20)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(vacantesVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(guardaVuelo)
                                        .addComponent(Cancelar)
                                        .addComponent(eliminarVuelo)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(idOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel10)
                                                .addComponent(origenReferencia)
                                                .addComponent(jLabel13))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel11)
                                                .addComponent(destinoReferencia)
                                                .addComponent(jLabel14)))))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(registrarAeropuerto)
                                .addComponent(cancelarRegAeropuertos))))
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVueloActionPerformed
        try {
            System.out.println(idVueloMain);
            vuelosController.destroy(idVueloMain);
            listarVuelos();
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(GestionVuelo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_eliminarVueloActionPerformed

    private void listaVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaVuelosMouseClicked
        int fila = listaVuelos.getSelectedRow();
        idVueloMain = Integer.parseInt((String)vuelosModel.getValueAt(fila, 0));
    }//GEN-LAST:event_listaVuelosMouseClicked

    private void listaAeropuertosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaAeropuertosMouseClicked
        int fila = listaAeropuertos.getSelectedRow();
        String[] referencia;
        referencia = new String[2];
        for (int i = 0; i < 2; i++) {
            referencia[i] = (String)ModelTableAeropuertos.getValueAt(fila, i);
        }
        
    }//GEN-LAST:event_listaAeropuertosMouseClicked

    private void registrarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarAeropuertoActionPerformed
        // TODO add your handling code here:
       int fila = listaAeropuertos.getSelectedRow();
        String ubicacion = (String)ModelTableAeropuertos.getValueAt(fila, 3);
        String avion = (String)ModelTableAeropuertos.getValueAt(fila, 0);      
        if(origenReferencia.getText()!="Ubicacion"){
            destinoReferencia.setText(ubicacion);
            idDestino.setText(avion);
            destinoVuelo.setText(ubicacion);
        }else{
            origenReferencia.setText(ubicacion);
            idOrigen.setText(avion);
            origenVuelo.setText(ubicacion);
        }   
    }//GEN-LAST:event_registrarAeropuertoActionPerformed

    private void cancelarRegAeropuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRegAeropuertosActionPerformed
        // TODO add your handling code here:
        origenReferencia.setText("Ubicacion");
        destinoReferencia.setText("Ubicacion");
        idOrigen.setText("");
        idDestino.setText("");
        origenVuelo.setText("");
        destinoVuelo.setText("");
    }//GEN-LAST:event_cancelarRegAeropuertosActionPerformed

    private void guardaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaVueloActionPerformed
        // TODO add your handling code here:
        
        try{
            Vuelo vuelo = new Vuelo();
        Avion avion = avionesController.findAvion(Integer.parseInt(idAvion.getText()));
        vuelo.setIdAvion(avion);
        vuelo.setOrigen(origenReferencia.getText());
        vuelo.setDestino(destinoReferencia.getText());
        vuelo.setFecha(fechaVuelo.getCalendar().getTime());
        vuelo.setVacantes(Integer.parseInt(vacantesVuelo.getText()));
        vuelo.setTiempoEstimado(BigDecimal.valueOf(Double.parseDouble(tiempoEstimadoVuelo.getText())));
        em.getTransaction().begin();
        em.persist(vuelo);
        em.flush();
        idVueloMain =vuelo.getIdVuelo();
        em.getTransaction().commit();
        em.close();
        System.out.println(idVueloMain);

        RefAeropuert refOrigen = new RefAeropuert();
        RefAeropuert refDestino = new RefAeropuert();
        Aeropuerto aeropuertoOrigen = new Aeropuerto();
        Aeropuerto aeropuertoDestino = new Aeropuerto();
        aeropuertoOrigen = aeropuertoController.findAeropuerto(Integer.parseInt(idOrigen.getText()));
        aeropuertoDestino = aeropuertoController.findAeropuerto(Integer.parseInt(idDestino.getText()));
        vuelo = vuelosController.findVuelo(idVueloMain);
        //Creacion de la referencia aeropuerto de origen
        refOrigen.setIdAeropuerto(aeropuertoOrigen);
        refOrigen.setIdVuelo(vuelo);
        refOrigen.setNombre("Origen");
        //Creacion de la referencia aeropuerto de destino
        refDestino.setIdAeropuerto(aeropuertoDestino);
        refDestino.setIdVuelo(vuelo);
        refDestino.setNombre("Destino");
        refController.create(refOrigen);
        refController.create(refDestino);
        listarVuelos();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
         
    }//GEN-LAST:event_guardaVueloActionPerformed

    private void listaAvionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaAvionesMouseClicked
        int row = listaAviones.getSelectedRow();
        idAvion.setText(ModelTableAviones.getValueAt(row, 0).toString());
        vacantesVuelo.setText(ModelTableAviones.getValueAt(row, 1).toString());
    }//GEN-LAST:event_listaAvionesMouseClicked

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        new GestionMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionVuelo().setVisible(true);
            }
        });
    }*/
    
    
    private void listarVuelos(){
        try{
            String[] modelTitles = {"ID Vuelo", "ID Avion", "Origen", "Destino", "Fecha", "Vacantes", "Tiempo estimado"};
            vuelosModel = new DefaultTableModel(null, modelTitles);
            List<Vuelo> vuelos =  vuelosController.findVueloEntities();
            String[] vuelo;
            vuelo = new String[7];
            for (Vuelo itvuelo : vuelos) {
                vuelo[0] = itvuelo.getIdVuelo().toString();
                vuelo[1] = itvuelo.getIdAvion().toStringId();
                vuelo[2] = itvuelo.getOrigen();
                vuelo[3] = itvuelo.getDestino();
                vuelo[4] = itvuelo.getFecha().toString();
                vuelo[5] = itvuelo.getVacantes().toString();
                vuelo[6] = itvuelo.getTiempoEstimado().toString();
                vuelosModel.addRow(vuelo);
            }
            listaVuelos.setModel(vuelosModel);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    } 
    
    private void listarAeropuertos(){
        try{
            String[] tableTitles = {"Id artopuerto", "Nombre", "Pagina Web", "Ciudad", "Pais"};
            ModelTableAeropuertos = new DefaultTableModel(null, tableTitles);
            List<Aeropuerto> aeropuertos =aeropuertoController.findAeropuertoEntities();
            String[] aeropuerto;
            aeropuerto = new String[5];
            for(Aeropuerto aero : aeropuertos){
                aeropuerto[0]=aero.getIdAeropuerto().toString();
                aeropuerto[1]=aero.getNombreAeropuerto();
                aeropuerto[2]=aero.getPaginaweb();
                aeropuerto[3]=aero.getCiudad();
                aeropuerto[4]=aero.getPais();
                ModelTableAeropuertos.addRow(aeropuerto);
            }
            listaAeropuertos.setModel(ModelTableAeropuertos);
                 
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    
 
    
    
    private void listarAviones(){
        try{
            List<VistaAviones> vistaAviones =  vistaAvionesController.findVistaAvionesEntities();
            String[] tableTitles = {"ID AVION", "CAPACIDAD", "MARCA", "ID AEROLINEA", "NOMBRE AEROLINEA"};
            ModelTableAviones = new DefaultTableModel(null, tableTitles);
            String[] aviones;
            aviones = new String[5];
            for (VistaAviones avione : vistaAviones) {
                aviones[0] = avione.getIdAvion()+"";
                aviones[1] = (String)avione.getCapacidad().toString();
                aviones[2] = avione.getMarca();
                aviones[3] = avione.getIdAerolinea()+"";
                aviones[4] = avione.getNombre();
                ModelTableAviones.addRow(aviones);
            }
            listaAviones.setModel(ModelTableAviones);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton cancelarRegAeropuertos;
    private javax.swing.JLabel destinoReferencia;
    private javax.swing.JLabel destinoVuelo;
    private javax.swing.JButton eliminarVuelo;
    private com.toedter.calendar.JDateChooser fechaVuelo;
    private javax.swing.JButton guardaVuelo;
    private javax.swing.JLabel idAvion;
    private javax.swing.JLabel idDestino;
    private javax.swing.JLabel idOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable listaAeropuertos;
    private javax.swing.JTable listaAviones;
    private javax.swing.JTable listaVuelos;
    private javax.swing.JLabel origenReferencia;
    private javax.swing.JLabel origenVuelo;
    private javax.swing.JButton registrarAeropuerto;
    private javax.swing.JButton regresar;
    private javax.swing.JTextPane tiempoEstimadoVuelo;
    private javax.swing.JLabel vacantesVuelo;
    // End of variables declaration//GEN-END:variables
}
