/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.vistas.usuario;

import com.sun.xml.internal.ws.wsdl.writer.UsingAddressing;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.control.ItinerarioJpaController;
import proyecto.control.PagoJpaController;
import proyecto.control.PasajeroJpaController;
import proyecto.control.ReservaJpaController;
import proyecto.control.UsuarioJpaController;
import proyecto.control.VueloJpaController;
import proyecto.entidades.Itinerario;
import proyecto.entidades.Pago;
import proyecto.entidades.Pasajero;
import proyecto.entidades.Reserva;
import proyecto.entidades.Usuario;
import proyecto.entidades.VistaReserva;
import proyecto.entidades.Vuelo;

/**
 *
 * @author David
 */
public class fReserva extends javax.swing.JFrame {
    private static int idVuelos[];
    private static int idReserva;
    private static String tipoReserva;
    private static PasajeroJpaController pasajerosController = new PasajeroJpaController();
    private static ReservaJpaController reservasController = new ReservaJpaController();
    private static VueloJpaController vuelosController = new VueloJpaController();
    private static ItinerarioJpaController itenarariosController = new ItinerarioJpaController();
    private static UsuarioJpaController usuariosController = new UsuarioJpaController();
    private static PagoJpaController pagosController = new PagoJpaController();

    private static Date currentDate = new GregorianCalendar().getTime();
    private static double totalPago;
    private static DefaultTableModel modelVuelos;
    /**
     * Creates new form fReserva
     */
    public fReserva(int idVuelos[], String tipoReserva, double total) {
        initComponents();
        this.idVuelos=idVuelos;
        this.tipoReserva = tipoReserva;
        this.totalPago = total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fechaIda = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        telefonoUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emailUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoDeDocumentoUsuario = new javax.swing.JComboBox<>();
        cedulaUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreApellidosUsuario = new javax.swing.JTextField();
        celularUsuario = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        kButton2 = new keeptoo.KButton();
        fechaRetorno = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        numeroTarjeta = new javax.swing.JTextField();
        nombreTitular = new javax.swing.JTextField();
        fechaVencTarjeta = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        codigoSeguridadTarjeta = new javax.swing.JTextField();
        documentoTitularTarjeta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        nombresPasajero = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        apellidosPasajero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tipoDocumentoPasajero = new javax.swing.JComboBox<>();
        cedulaPasajero = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        radioBtnHombre = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        radioBtnMujer = new javax.swing.JRadioButton();
        fechaNacimientoPasajero = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        edadPasajero = new com.toedter.components.JSpinField();
        kButton1 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        jLabel28 = new javax.swing.JLabel();
        kButton7 = new keeptoo.KButton();
        kButton8 = new keeptoo.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVuelos = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(168, 192, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(233, 231, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jLabel11.setText("Fecha");

        jLabel12.setText("Ida");

        jLabel14.setText("Información de la reserva");

        telefonoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        telefonoUsuario.setOpaque(false);

        jLabel10.setText("Teléfono");

        emailUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        emailUsuario.setOpaque(false);

        jLabel8.setText("e-mail");

        jLabel9.setText("Información de contacto");

        jLabel4.setText("Tipo de documento");

        tipoDeDocumentoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Pasaporte" }));
        tipoDeDocumentoUsuario.setOpaque(false);

        cedulaUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cedulaUsuario.setOpaque(false);
        cedulaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Cédula de identidad");

        jLabel6.setText("Nombres y apellidos");

        nombreApellidosUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nombreApellidosUsuario.setOpaque(false);

        celularUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        celularUsuario.setOpaque(false);
        celularUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularUsuarioActionPerformed(evt);
            }
        });

        jLabel27.setText("Celular");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Información de factura");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel29.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel29.setMaximumSize(new java.awt.Dimension(39, 14));

        kButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-checked-radio-button-24.png"))); // NOI18N
        kButton2.setText("Aceptar");
        kButton2.setkEndColor(new java.awt.Color(140, 126, 242));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(170, 61, 250));
        kButton2.setkStartColor(new java.awt.Color(204, 176, 252));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        jLabel13.setText("Retorno");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Total");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cedulaUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreApellidosUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                            .addComponent(tipoDeDocumentoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(telefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(celularUsuario)))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel14))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(49, 49, 49)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fechaIda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoDeDocumentoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreApellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celularUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(fechaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fechaIda, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 57, -1, 720));

        jPanel2.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Pago con tarjeta de crédito");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel7.setMaximumSize(new java.awt.Dimension(39, 14));

        numeroTarjeta.setEditable(false);
        numeroTarjeta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        numeroTarjeta.setOpaque(false);

        nombreTitular.setEditable(false);
        nombreTitular.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nombreTitular.setOpaque(false);

        fechaVencTarjeta.setEditable(false);
        fechaVencTarjeta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        fechaVencTarjeta.setOpaque(false);

        jLabel15.setText("Número de tarjeta");

        jLabel16.setText("Titular de la tarjeta");

        jLabel17.setText("Vencimiento");

        jLabel18.setText("Código de seguridad");

        codigoSeguridadTarjeta.setEditable(false);
        codigoSeguridadTarjeta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        codigoSeguridadTarjeta.setOpaque(false);
        codigoSeguridadTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoSeguridadTarjetaActionPerformed(evt);
            }
        });

        documentoTitularTarjeta.setEditable(false);
        documentoTitularTarjeta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        documentoTitularTarjeta.setOpaque(false);
        documentoTitularTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTitularTarjetaActionPerformed(evt);
            }
        });

        jLabel19.setText("Documento del titular");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nombreTitular, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numeroTarjeta, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fechaVencTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19))
                                    .addGap(53, 53, 53)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(codigoSeguridadTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(documentoTitularTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaVencTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoSeguridadTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(documentoTitularTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 57, -1, -1));

        jPanel3.setOpaque(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Agreagar pasajero");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel20.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel20.setMaximumSize(new java.awt.Dimension(39, 14));

        nombresPasajero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        nombresPasajero.setOpaque(false);

        jLabel21.setText("Nombres");

        jLabel22.setText("Apellidos");

        apellidosPasajero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        apellidosPasajero.setOpaque(false);
        apellidosPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosPasajeroActionPerformed(evt);
            }
        });

        jLabel24.setText("Tipo de documento");

        tipoDocumentoPasajero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Reserva" }));

        cedulaPasajero.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        cedulaPasajero.setOpaque(false);

        jLabel25.setText("Cédula");

        radioBtnHombre.setText("Hombre");
        radioBtnHombre.setOpaque(false);
        radioBtnHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnHombreActionPerformed(evt);
            }
        });

        jLabel26.setText("Sexo");

        radioBtnMujer.setText("Mujer");
        radioBtnMujer.setOpaque(false);
        radioBtnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMujerActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha de nacimiento");

        jLabel23.setText("Edad");

        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-add-user-male-16.png"))); // NOI18N
        kButton1.setText("Agregar");
        kButton1.setkEndColor(new java.awt.Color(140, 126, 242));
        kButton1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(170, 61, 250));
        kButton1.setkStartColor(new java.awt.Color(204, 176, 252));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-eraser-16.png"))); // NOI18N
        kButton3.setText("Limpiar");
        kButton3.setkEndColor(new java.awt.Color(140, 126, 242));
        kButton3.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton3.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(170, 61, 250));
        kButton3.setkStartColor(new java.awt.Color(204, 176, 252));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21)
                    .addComponent(nombresPasajero)
                    .addComponent(jLabel22)
                    .addComponent(apellidosPasajero)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaNacimientoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tipoDocumentoPasajero, 0, 91, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(edadPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(cedulaPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25)
                                    .addComponent(radioBtnMujer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radioBtnHombre, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jLabel26))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombresPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidosPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaNacimientoPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDocumentoPasajero)
                    .addComponent(cedulaPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBtnMujer))
                    .addComponent(edadPasajero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtnHombre)
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );

        kGradientPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 57, -1, -1));

        jLabel28.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Reserva");
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel28.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel28.setMaximumSize(new java.awt.Dimension(39, 14));
        kGradientPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1750, 40));

        kButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-airplane-take-off-16.png"))); // NOI18N
        kButton7.setText("Terminar registro");
        kButton7.setkEndColor(new java.awt.Color(66, 41, 253));
        kButton7.setkHoverEndColor(new java.awt.Color(151, 255, 151));
        kButton7.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton7.setkHoverStartColor(new java.awt.Color(69, 230, 26));
        kButton7.setkStartColor(new java.awt.Color(157, 155, 220));
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1580, 880, 150, 33));

        kButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-back-arrow-16.png"))); // NOI18N
        kButton8.setText("Regresar");
        kButton8.setkEndColor(new java.awt.Color(140, 126, 242));
        kButton8.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton8.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton8.setkHoverStartColor(new java.awt.Color(170, 61, 250));
        kButton8.setkStartColor(new java.awt.Color(204, 176, 252));
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 110, 97, 33));

        listaVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(listaVuelos);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 470, 160));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setText("Vuelos reservados");
        kGradientPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 800, 470, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1757, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoSeguridadTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoSeguridadTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoSeguridadTarjetaActionPerformed

    private void documentoTitularTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTitularTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTitularTarjetaActionPerformed

    private void radioBtnHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnHombreActionPerformed
        // TODO add your handling code here:
        if(radioBtnHombre.isSelected()){
            radioBtnMujer.setSelected(false);
        }
    }//GEN-LAST:event_radioBtnHombreActionPerformed

    private void celularUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularUsuarioActionPerformed

    private void apellidosPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosPasajeroActionPerformed

    private void radioBtnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMujerActionPerformed
        // TODO add your handling code here:
        if(radioBtnMujer.isSelected()){
            radioBtnHombre.setSelected(false);
        }
    }//GEN-LAST:event_radioBtnMujerActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
       try {
            Pasajero pasajero = new Pasajero();
            Reserva reserva = new Reserva();
            reserva = reservasController.findReserva(idReserva);
            pasajero.setIdReserva(reserva);
            pasajero.setCedula(cedulaPasajero.getText());
            pasajero.setEdad(edadPasajero.getValue());
            pasajero.setFechaNacimiento(fechaNacimientoPasajero.getCalendar().getTime());
            pasajero.setNombre(apellidosPasajero.getText() + " " + nombresPasajero.getText());
            pasajero.setTipoDocumento(tipoDocumentoPasajero.getSelectedItem().toString());
            if (radioBtnHombre.isSelected()) {
                pasajero.setGenero(radioBtnHombre.getText());
            } else if (radioBtnMujer.isSelected()) {
                pasajero.setGenero(radioBtnMujer.getText());
            }
            pasajerosController.create(pasajero);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }finally{
           JOptionPane.showMessageDialog(null, "Pasajero agregado");
           
       }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        try {
            fechasVuelos();
             EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proyecto_DespegarPU");
            EntityManager em = emf.createEntityManager();
            
            Usuario usuario = new Usuario();
            Reserva reserva = new Reserva();
            //creacion del usuario
            usuario.setCedula(cedulaUsuario.getText());
            usuario.setCelular(celularUsuario.getText());
            usuario.setNombre(nombreApellidosUsuario.getText());
            usuario.setTelefono(telefonoUsuario.getText());
            usuario.setTipoDocumento(tipoDeDocumentoUsuario.getSelectedItem().toString());
            usuario.setEmail(emailUsuario.getText());
            reserva.setEstado("Creador");
            reserva.setFechaRegistro(new GregorianCalendar().getTime());
            reserva.setTipo(tipoReserva);
            reserva.setTotal(BigDecimal.valueOf(totalPago));
            em.getTransaction().begin();
            em.persist(usuario);
            em.flush();
            reserva.setIdUsuario(usuario);
            em.persist(reserva);
            em.flush();
            idReserva = reserva.getIdReserva();
            System.out.println("El id de la reserva creda es:"+idReserva);
            em.getTransaction().commit();
            em.close();
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }finally{
            numeroTarjeta.setEditable(true);
            nombreTitular.setEditable(true);
            documentoTitularTarjeta.setEditable(true);
            fechaVencTarjeta.setEditable(true);
            codigoSeguridadTarjeta.setEditable(true);
        }
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        // TODO add your handling code here:
        
        nombresPasajero.setText("");
        apellidosPasajero.setText("");
        cedulaPasajero.setText("");
        
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        // TODO add your handling code here:
        try{
            Pago pago = new Pago();
            pago.setCodigoSeguridad(codigoSeguridadTarjeta.getText());
            pago.setDocumentoTitular(documentoTitularTarjeta.getText());
            pago.setFechaVencimiento(fechaVencTarjeta.getText());
            pago.setNumeroTarjeta(numeroTarjeta.getText());
            pago.setTitular(nombreTitular.getText());
            pagosController.create(pago);
            persistirItinerarios();
            JOptionPane.showMessageDialog(null, "La reserva se ha generado con éxito con el código: "+idReserva);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString(), "Error al finalizar el registro",ERROR);
        }finally{
            listarVuelos();
        }
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
        new VentanaPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kButton8ActionPerformed

    private void cedulaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int a[] = {1};
                new fReserva(a, "Solo Ida", 45.5).setVisible(true);
            }
        });
    }
    
    
    private void persistirItinerarios(){
        try{
            int length = idVuelos.length;
        Itinerario itinerario;    
        Vuelo vuelo;
        Reserva reserva = new Reserva();
        reserva = reservasController.findReserva(idReserva);
        
        for (int i = 0; i < length; i++) {
            vuelo = vuelosController.findVuelo(idVuelos[i]);
            itinerario = new Itinerario();
            itinerario.setIdVuelo(vuelo);
            itinerario.setIdReserva(reserva);
            itinerario.setFecha(currentDate);
            itenarariosController.create(itinerario);
        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    private void listarVuelos(){
        try{
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proyecto_DespegarPU");
            EntityManager em = emf.createEntityManager();
            em = emf.createEntityManager();
            em.getTransaction();
            Query query = em.createNativeQuery("SELECT * FROM vistaReserva where ID_RESERVA="+idReserva, VistaReserva.class);
            List<VistaReserva> vuelos = query.getResultList();
            String[] titulos = {"ID RESERVA", "FECHA REGISTRO", "FECHA DE VUELO", "ORIGEN", "DESTINO"};
            modelVuelos = new DefaultTableModel(null, titulos);
            String[] rowvuelo = new String[5];
            for (VistaReserva vuelo : vuelos) {
                rowvuelo[0] = vuelo.getIdReserva()+"";
                rowvuelo[1] = vuelo.getFechaRegistro().toString();
                rowvuelo[2] = vuelo.getFecha().toString();
                rowvuelo[3] = vuelo.getOrigen();
                rowvuelo[4] = vuelo.getDestino();
                modelVuelos.addRow(rowvuelo);
            }
            
            listaVuelos.setModel(modelVuelos);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    private void fechasVuelos(){
        Vuelo vuelo = new Vuelo();
        if(idVuelos.length>1){
            vuelo = vuelosController.findVuelo(idVuelos[0]);
            fechaIda.setText(vuelo.getFecha().toString());
            vuelo = vuelosController.findVuelo(idVuelos[1]);
            fechaRetorno.setText(vuelo.getFecha().toString());
        }else if(idVuelos.length==1){
            vuelo = vuelosController.findVuelo(idVuelos[0]);
            fechaIda.setText(vuelo.getFecha().toString());
        }
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosPasajero;
    private javax.swing.JTextField cedulaPasajero;
    private javax.swing.JTextField cedulaUsuario;
    private javax.swing.JTextField celularUsuario;
    private javax.swing.JTextField codigoSeguridadTarjeta;
    private javax.swing.JTextField documentoTitularTarjeta;
    private com.toedter.components.JSpinField edadPasajero;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JLabel fechaIda;
    private com.toedter.calendar.JDateChooser fechaNacimientoPasajero;
    private javax.swing.JLabel fechaRetorno;
    private javax.swing.JTextField fechaVencTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KButton kButton7;
    private keeptoo.KButton kButton8;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable listaVuelos;
    private javax.swing.JTextField nombreApellidosUsuario;
    private javax.swing.JTextField nombreTitular;
    private javax.swing.JTextField nombresPasajero;
    private javax.swing.JTextField numeroTarjeta;
    private javax.swing.JRadioButton radioBtnHombre;
    private javax.swing.JRadioButton radioBtnMujer;
    private javax.swing.JTextField telefonoUsuario;
    private javax.swing.JComboBox<String> tipoDeDocumentoUsuario;
    private javax.swing.JComboBox<String> tipoDocumentoPasajero;
    // End of variables declaration//GEN-END:variables
}
