/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.vistas.usuario;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.control.VistaVuelosJpaController;
import proyecto.entidades.VistaVuelos;

/**
 *
 * @author David
 */
public class IdaVueltaResultados extends javax.swing.JFrame {
    private static VistaVuelosJpaController controladorVistaVuelos = new VistaVuelosJpaController();
    private static DefaultTableModel ModeloVuelosIda = new DefaultTableModel();
    private static DefaultTableModel ModeloVuelosRegreso = new DefaultTableModel();
    private static EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proyecto_DespegarPU");
    private static EntityManager em = emf.createEntityManager();
    private static String origen;
    private static String destino;
    private static Date fechaIda;
    private static Date fechaRetorno;
    private static int nAdultos;
    private static int nMenores;
    private static int idVueloIdaSelected;
    private static int idVueloRetornoSelected;
    private static double totalPago;
    private static String claseVuelo;
    
    /**
     * Creates new form IdaVuelta
     */
    public IdaVueltaResultados(String origen, String destino, Date fechaIda, int nAdultos, int nMenores, Date fechaRetorno, String claseVuelo) {
        this.origen = origen;
        this.destino = destino;
        this.fechaIda = fechaIda;
        this.nAdultos = nAdultos;
        this.nMenores = nMenores;
        this.fechaRetorno = fechaRetorno;
        this.claseVuelo = claseVuelo;
        initComponents();
        listarResultadosIda(this.origen, this.destino, this.fechaIda,this.nAdultos+this.nMenores);
        listarResultadosRetorno(this.destino, this.origen, this.fechaRetorno,this.nAdultos+this.nMenores);
        System.out.println(claseVuelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idVueloRetorno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        origenRetorno = new javax.swing.JLabel();
        destinoRetorno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        precioRetorno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idVueloIda = new javax.swing.JLabel();
        origenIda = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        destinoIda = new javax.swing.JLabel();
        precioIda = new javax.swing.JLabel();
        totalSeleccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        opcionesRetorno = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        opcionesIda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(123, 123, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(253, 166, 253));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Total de seleccion");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Información vuelo de retorno");

        jLabel7.setText("ID Vuelo");

        jLabel8.setText("Origen");

        jLabel14.setText("Destino");

        jLabel9.setText("Precio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                            .addComponent(jLabel14)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precioRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destinoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idVueloRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origenRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idVueloRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(origenRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destinoRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioRetorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Información vuelo de ida");

        jLabel6.setText("ID Vuelo");

        jLabel11.setText("Origen");

        jLabel12.setText("Destino");

        jLabel13.setText("Precio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(destinoIda, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(origenIda, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idVueloIda, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precioIda, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idVueloIda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(origenIda, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(destinoIda, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(precioIda, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalSeleccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalSeleccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        opcionesRetorno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        opcionesRetorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionesRetornoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(opcionesRetorno);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vuelos de retorno");

        opcionesIda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        opcionesIda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcionesIdaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(opcionesIda);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vuelos de ida");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Resultados de busqueda");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel2.setMaximumSize(new java.awt.Dimension(39, 14));

        kButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-ball-point-pen-16.png"))); // NOI18N
        kButton1.setText("Reservar");
        kButton1.setkEndColor(new java.awt.Color(140, 126, 242));
        kButton1.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(170, 61, 250));
        kButton1.setkStartColor(new java.awt.Color(204, 176, 252));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/imgs/icons8-back-arrow-16.png"))); // NOI18N
        kButton2.setText("Regresar");
        kButton2.setkEndColor(new java.awt.Color(140, 126, 242));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(170, 61, 250));
        kButton2.setkStartColor(new java.awt.Color(204, 176, 252));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalSeleccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(119, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1257, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionesIdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesIdaMouseClicked
        // TODO add your handling code here:
        try {
            int row = opcionesIda.getSelectedRow();
            double total;
            double totalMenores;
            double totalMayores;
            totalMenores = Double.parseDouble(ModeloVuelosIda.getValueAt(row, 5).toString()) * nMenores * 0.5;
            totalMayores = Double.parseDouble(ModeloVuelosIda.getValueAt(row, 5).toString()) * nAdultos;
            total = totalMenores + totalMayores;
            if (claseVuelo == "Económica") {
                total = total;
            }
            if (claseVuelo == "Premium economy") {
                total = total + total * 0.2;
            }
            if (claseVuelo == "Ejecutiva/Busines") {
                total = total + total * 0.5;
            }
            if (claseVuelo == "Primera clase") {
                total = total * 0.7 + total;
            }
            idVueloIda.setText(ModeloVuelosIda.getValueAt(row, 0).toString());
            origenIda.setText(ModeloVuelosIda.getValueAt(row, 3).toString());
            destinoIda.setText(ModeloVuelosIda.getValueAt(row, 4).toString());
            precioIda.setText(String.valueOf(total));
            idVueloIdaSelected = Integer.parseInt(ModeloVuelosIda.getValueAt(row, 0).toString());
            if (precioRetorno.getText() == "") {
                totalSeleccion.setText(String.valueOf(total));
                System.out.println(total);
            } else if (precioRetorno.getText() != "") {
                double totalCalculado;
                totalCalculado = Double.parseDouble(precioRetorno.getText().toString()) + Double.parseDouble(precioIda.getText().toString());
                totalSeleccion.setText(String.valueOf(totalCalculado));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_opcionesIdaMouseClicked

    private void opcionesRetornoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcionesRetornoMouseClicked
        try {
            int row = opcionesRetorno.getSelectedRow();
            double totalRetorno;
            double totalMenores = Double.parseDouble(ModeloVuelosRegreso.getValueAt(row, 5).toString()) * nMenores * 0.5;
            double totalMayores = Double.parseDouble(ModeloVuelosRegreso.getValueAt(row, 5).toString()) * nAdultos;
            totalRetorno = totalMayores + totalMenores;
            if (claseVuelo == "Económica") {
                totalRetorno = totalRetorno;
            }
            if (claseVuelo == "Premium economy") {
                totalRetorno = totalRetorno + totalRetorno * 0.2;
            }
            if (claseVuelo == "Ejecutiva/Busines") {
                totalRetorno = totalRetorno + totalRetorno * 0.5;
            }
            if (claseVuelo == "Primera clase") {
                totalRetorno = totalRetorno * 0.7 + totalRetorno;
            }
            idVueloRetorno.setText(ModeloVuelosRegreso.getValueAt(row, 0).toString());
            origenRetorno.setText(ModeloVuelosRegreso.getValueAt(row, 3).toString());
            destinoRetorno.setText(ModeloVuelosRegreso.getValueAt(row, 4).toString());
            precioRetorno.setText(String.valueOf(totalRetorno));
            idVueloRetornoSelected = Integer.parseInt(ModeloVuelosRegreso.getValueAt(row, 0).toString());
            if (precioIda.getText() == "") {
                totalSeleccion.setText(String.valueOf(totalRetorno));
            } else if (precioIda.getText() != "") {
                double totalCalculado;
                totalCalculado = Double.parseDouble(precioRetorno.getText().toString()) + Double.parseDouble(precioIda.getText().toString());
                totalSeleccion.setText(String.valueOf(totalCalculado));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
            
    }//GEN-LAST:event_opcionesRetornoMouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        totalPago = Double.parseDouble(totalSeleccion.getText());
        int[] vuelos = {idVueloIdaSelected, idVueloRetornoSelected};
        new fReserva(vuelos, "Ida y vuelta", totalPago, nAdultos+nMenores).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        new FormBusqueda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
/*    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IdaVueltaResultados("Quio", "Madrid", new GregorianCalendar(3920, 10, 10).getTime(), 1, 1, new GregorianCalendar(3920, 10, 12).getTime(), "Primera clase").setVisible(true);
            }
        });
    }*/
    
    
    
    
    private void listarResultadosIda(String origen, String destino, Date fecha, int pasajeros) {
        try {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proyecto_DespegarPU");
            EntityManager em = emf.createEntityManager();
            String fechaQ = new SimpleDateFormat("yyyy-MM-dd").format(fecha);
            
            Query query = em.createNativeQuery("SELECT * FROM VISTA_VUELOS AS V WHERE V.ORIGEN='"+origen+"' AND v.destino='"+destino+"' AND v.FECHA='"+fechaQ+"' AND v.VACANTES>"+pasajeros+"", VistaVuelos.class);
            List<VistaVuelos> vuelos = query.getResultList();
            if(vuelos.size()==0){
                JOptionPane.showMessageDialog(null, "No se han encontrado vuelos en el sistema para los datos especificados, vuelva a la ventana de busqueda y realice otra busqueda");
                return;
            }
            
            String[] tableTitles = {"ID VUELO", "FECHA", "VACANTES","ORIGEN", "DESTINO", "PRECIO", "VACANTES", "AEROLINEA","ID AVION","MODELO"};
            
            ModeloVuelosIda = new DefaultTableModel(null, tableTitles);
            String[] vuelo;
            vuelo = new String[10];
            for (VistaVuelos iteVuelo : vuelos) {
                vuelo[0] = iteVuelo.getIdVuelo()+"";
                vuelo[1] = iteVuelo.getFecha()+"";
                vuelo[2] = iteVuelo.getVacantes().toString();
                vuelo[3] = iteVuelo.getOrigen();
                vuelo[4] = iteVuelo.getDestino();
                vuelo[5] = iteVuelo.getTiempoEstimado().toString();
                vuelo[6] = iteVuelo.getVacantes().toString();
                vuelo[7] = iteVuelo.getNombre();
                vuelo[8] = iteVuelo.getIdAvion()+"";
                vuelo[9] = iteVuelo.getModelo();
                ModeloVuelosIda.addRow(vuelo);
            }
            opcionesIda.setModel(ModeloVuelosIda);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    private void listarResultadosRetorno(String origen, String destino, Date fecha, int pasajeros) {
        try {
             System.out.println("Origen " + origen + "Destino "+destino+"Fecha "+fecha);
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Proyecto_DespegarPU");
            EntityManager em = emf.createEntityManager();
            String fechaQ = new SimpleDateFormat("yyyy-MM-dd").format(fecha);
            
            Query query = em.createNativeQuery("SELECT * FROM VISTA_VUELOS AS V WHERE V.ORIGEN='"+origen+"' AND v.destino='"+destino+"' AND v.FECHA='"+fechaQ+"' AND v.VACANTES>"+pasajeros+"", VistaVuelos.class);
            List<VistaVuelos> vuelos = query.getResultList();
            if(vuelos.size()==0){
                JOptionPane.showMessageDialog(null, "No se han encontrado vuelos en el sistema para los datos especificados, vuelva a la ventana de busqueda y realice otra busqueda");
                return;
            }
            for (VistaVuelos vuelo : vuelos) {
                System.out.println(vuelo.getOrigen());
            }
            
            String[] tableTitles = {"ID VUELO", "FECHA", "VACANTES","ORIGEN", "DESTINO", "PRECIO", "VACANTES", "AEROLINEA","ID AVION","MODELO"};
            ModeloVuelosRegreso = new DefaultTableModel(null, tableTitles);
            String[] vuelo;
            vuelo = new String[10];
            for (VistaVuelos iteVuelo : vuelos) {
                vuelo[0] = iteVuelo.getIdVuelo()+"";
                vuelo[1] = iteVuelo.getFecha()+"";
                vuelo[2] = iteVuelo.getVacantes().toString();
                vuelo[3] = iteVuelo.getOrigen();
                vuelo[4] = iteVuelo.getDestino();
                vuelo[5] = iteVuelo.getTiempoEstimado().toString();
                vuelo[6] = iteVuelo.getVacantes().toString();
                vuelo[7] = iteVuelo.getNombre();
                vuelo[8] = iteVuelo.getIdAvion()+"";
                vuelo[9] = iteVuelo.getModelo();
                ModeloVuelosRegreso.addRow(vuelo);
            }
            opcionesRetorno.setModel(ModeloVuelosRegreso);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinoIda;
    private javax.swing.JLabel destinoRetorno;
    private javax.swing.JLabel idVueloIda;
    private javax.swing.JLabel idVueloRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable opcionesIda;
    private javax.swing.JTable opcionesRetorno;
    private javax.swing.JLabel origenIda;
    private javax.swing.JLabel origenRetorno;
    private javax.swing.JLabel precioIda;
    private javax.swing.JLabel precioRetorno;
    private javax.swing.JLabel totalSeleccion;
    // End of variables declaration//GEN-END:variables
}
